### ISSUE TITLE
Несколько авторов у книги

### ISSUE THREAD

**Issue by loveorigami** [yurii-github/yii2-mylib#6]
Есть очень много книг-сборников.
Например
http://www.loveorigami.info/oriwiki/BOS-2004_(Manchester)

В этом сборнике очень много авторов.
Которые в свою очередь имеют свои отдельные книги

Например
http://www.loveorigami.info/oriwiki/Terry_Nicolas

Задача - получить книги одного автора, или получить книги (сборники), в которых этот автор упоминается.

**Comment by yurii-github** [comment]
извиняюсь, что так долго не отвечал. я честно даже не заметил твои сообщения.. :/

у меня задача стояла чтобы была одна таблица excel и название файлов обновлялось само.
Я думал сначала заморачиваться с авторами, но потом передумал. Если несколько авторов, то я их добавляю в поле author через запятую. Ищу по имени в фильтре.

![image](https://user-images.githubusercontent.com/1162656/54883656-a26f0800-4e70-11e9-835c-27a2da71e2b9.png)

![image](https://user-images.githubusercontent.com/1162656/54883714-45278680-4e71-11e9-9140-82a6b8c710fa.png)

или что имелось в виду?

**Comment by yurii-github** [comment]
если актуально, переоткрывай
